depends_on = ["3-docking_preparation", "4-docking"]
inputs = ["*.pdb", "docking_results"]
outputs = ["results"]

[container]
docker_image = "chiral.sakuracr.jp/smina:2025_11_06"

[scripts]
pre_run = ""
post_run = ""

