depends_on = ["1-protein_preparation"]
inputs = ["*.pdb"]
outputs = ["*.pdb", "config.txt", "ligand_list.txt", "real_ligand.sdf"]

[container]
docker_image = "chiral.sakuracr.jp/smina:2025_11_06"

[scripts]
pre_run = ""
post_run = ""

