depends_on = ["1-protein_preparation", "3-docking_preparation"]
inputs = ["*.pdb", "real_ligand.sdf"]
outputs = ["*.sdf", "ligand_library", "variants.svg", "ligand.csv", "ligands.zip", "constructed_library", "selected_compounds"]

[container]
docker_image = "chiral.sakuracr.jp/smina:2025_11_06"

[scripts]

