depends_on = ["ligand_unpack"]
inputs = ["*.sdf", "ligand_library"]
outputs = ["*.sdf", "ligand_library", "variants.svg", "ligand.csv", "outputs/selected_compounds"]

[container]
docker_image = "chiral.sakuracr.jp/smina:2025_11_06"

[scripts]
run = "./run.sh"

